// Generated by FlutterFire CLI. Run `flutterfire configure` to regenerate.
// Copy this file from firebase_options.dart.example and fill in your values,
// or run: flutterfire configure --project=hizmatai
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY', defaultValue: 'YOUR_WEB_API_KEY'),
    authDomain: 'hizmatai.firebaseapp.com',
    projectId: 'hizmatai',
    storageBucket: 'hizmatai.firebasestorage.app',
    messagingSenderId: '331814655614',
    appId: '1:331814655614:web:9551b3a5935b9df3192a2f',
    measurementId: 'G-X5S80XTF21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY', defaultValue: 'YOUR_ANDROID_API_KEY'),
    projectId: 'hizmatai',
    storageBucket: 'hizmatai.firebasestorage.app',
    messagingSenderId: '331814655614',
    appId: '1:331814655614:android:2abf58be4d244808192a2f',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY', defaultValue: 'YOUR_IOS_API_KEY'),
    projectId: 'hizmatai',
    storageBucket: 'hizmatai.firebasestorage.app',
    messagingSenderId: '331814655614',
    appId: '1:331814655614:ios:483e4f2e8e450c9e192a2f',
  );
}
